# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6576f015a0308b86fd016db95876a8df3e3a130ef24ee0742a3f744c3562fd3b7b24aae32b39dd852bc91e6b630f25c0137a5ecce37e2a05e07728006f5c2f2

test:
  secret_key_base: 71cf0f1acb0cbf14f64aa53f8345c0728114f9933736c225487af338bac9225ab57e45b41f4dd203216a304421436a26e0912e433316d025743e04abd7f8f3f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
